#!/bin/bash

# Run any commands before pull
eval $BEFORE_PULL_COMMANDS

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd /code
git pull

# Run any commands after pull
eval $AFTER_PULL_COMMANDS