#!/bin/bash

# Custom scripts
source /usr/bin/run_custom_scripts_before_push.sh

# Run any commands before push
eval $BEFORE_PUSH_COMMANDS

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

timestamp() {
  date +"%D %T"
}
ts=$(timestamp)
cd /code
git add *
git commit -a -m "push from container $ts"
git push

# Run any commands after push
eval $AFTER_PUSH_COMMANDS

# Custom scripts
source /usr/bin/run_custom_scripts_after_push.sh